система подсчета соседей
PashKo76/Minesweeper2 pull request #3
Opened 2022-11-27 15:36 UTC by PashKo76

Количество соседей в клетке не храниться, но хранится инфа о наличии соседа храниться, это потребуется в системе видимости

2022-11-28 05:35 UTC, stg34 requested changes

2022-11-28 05:35 UTC, stg34 commented on MineSweeper2/MineSweeper2/Cell.cs
> +            //if (IsOpen)
Комментари тут создают шум и ломают отступы. Почисти

2022-11-28 05:35 UTC, stg34 commented on MineSweeper2/MineSweeper2/Cell.cs
> +                HaveMineNeigh = true;
Эта переменная нигде не используется

2022-11-28 05:35 UTC, stg34 commented on MineSweeper2/MineSweeper2/Cell.cs
> +            for(int t = 0; t < 8; t++)
Фокусы с синусом и косинусом можно записать проще. Ведь требуется просто перебрать окружающие 8 координат:

```
for(int dx = -1; dx <= 1; dx++) 
{
    for(int dy = -1; dy <= 1; dy++) 
    {
        if (dy != 0 && dx != 0)
        {
             if(field.IsCellMine(x+dx, y+dy)) 
             {
                  ........
             }
        }
    }
}
```

2022-11-28 05:39 UTC, stg34 requested changes

2022-11-28 05:39 UTC, stg34 commented on MineSweeper2/MineSweeper2/Field.cs
> +        public bool IsCellMine(int x, int y)
Этот метод совсем никуда не годится.
1. Если мы захотим проверить, является ли ячейка пустой/открытой/с флажком/... то у нас будут образовываться пары методов: один в ячейке (IsMine, IsEmpty, ...) и один такой же в Field (IsCellMine(), IsCellOpen(), ...) Лучше сделать универсальный метод у Field, который вернет ячейку по ее координатам, а мы потом полученную ячейку спросим на интересующий нас вопрос:
```
cell = field.cellAt(x, y)
cell.IsMine
cell.IsEmpty
```

2. Подозрительное поведение при выходе за границы поля. лучше убрать отсюда проверку на выход за границы поля, пусть падает с ошибкой. Добавить метод Field.isCoordValid(x, y), который вернет true если координаты в передах поля или false в противном слкчае, и использовать явно перед обращением к ячейке по координатам. В дальнейшем можно будет сделать более хитрую схему, но пока давай сделаем самым простым споосбом

2022-11-28 17:24 UTC, PashKo76 commented on MineSweeper2/MineSweeper2/Cell.cs
> +                HaveMineNeigh = true;
переменную я изменяю для последующего расчета видимости, а точнее если у клетки из соседей только мины и такие "особо" открытые клетки она автоматом не откроется, и наоборот если есть хоть одна нормальная клетка без соседей мин она её откроет

2022-11-28 17:29 UTC, PashKo76 commented on MineSweeper2/MineSweeper2/Field.cs
> +        public bool IsCellMine(int x, int y)
раньше я использовал телепортацию из клеточных автоматов(поле без границ или иллюзию бесконечности) когда вместо ошибки возвращало значение с другого конца массива

2022-11-28 17:30 UTC, PashKo76 commented on MineSweeper2/MineSweeper2/Cell.cs
> +            for(int t = 0; t < 8; t++)
забавно но к этому методу я и сам пришел сегодня в школе

2022-11-28 17:35 UTC, PashKo76 commented on MineSweeper2/MineSweeper2/Cell.cs
> +                HaveMineNeigh = true;
в предыдущем прототипе это было особенно заметно

2022-11-28 19:35 UTC, PashKo76 commented on MineSweeper2/MineSweeper2/Field.cs
> +        public bool IsCellMine(int x, int y)
![image](https://user-images.githubusercontent.com/119113475/204365123-6ffccc7a-a697-456e-aceb-a967fec8028c.png)
![image](https://user-images.githubusercontent.com/119113475/204365158-d6b9318c-5afc-4cb1-a132-7e8afee97386.png)
Странный баг

2022-11-28 19:36 UTC, PashKo76 commented on MineSweeper2/MineSweeper2/Field.cs
> +        public bool IsCellMine(int x, int y)
![image](https://user-images.githubusercontent.com/119113475/204365295-6316bef4-0441-4e24-be7e-eea2042d4460.png)
![image](https://user-images.githubusercontent.com/119113475/204365393-d33cbd70-5315-4c75-b920-c22d3c049274.png)
и не менее странный фикс

2022-11-30 13:54 UTC, merged

2022-12-04 12:21 UTC, stg34 commented on MineSweeper2/MineSweeper2/Field.cs
> +        public bool DoesCordExist(int x, int y)
if (x < 0)  return false
if (x > width)  return false
if (y < 0)  return false
if (y > height)  return false
return true

2022-12-04 12:25 UTC, stg34 commented on MineSweeper2/MineSweeper2/Cell.cs
> +                    if(dx != 0 || dy != 0)
(dx != 0 || dy != 0) && field.DoesCordExist(X + dx, Y + dy)